<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">

		<title>YouTube OAuth Collector</title>

		<style>
			body {
				padding: 30px;
			}
			.btn {
				padding: 10px 30px;
				background-color: #888888;
				color: white;
				border: 1px solid black;
				text-decoration: none;
			}
			.error {
				color: darkred;
				font-family: monospace;
				white-space: pre;
			}
		</style>
	</head>

	<body>
		<h1>YouTube OAuth Collector</h1>
		<?php if(@$goto): ?>

			<p>Click the following button to go to YouTube and select the channel you want us to publish to.</p>
			<a class="btn" href="<?php echo h($goto)?>">Go to YouTube</a>


		<?php elseif(@$error): ?>

			<p class="error"><?php echo h($error)?></p>
			<p>Click here to <a href="<?php echo h($baseurl)?>">start again</a></p>

		<?php elseif(@$success): ?>

			<h2>Thank you!</h2>
			<p>The mighty Luckycat will now publish wonderful cat-content to your channel <strong><?=h($channel)?></strong>!</p>
			<p style="margin-top: 100px; color: #ccc;">If you have superuser or admin rights in the corresponding <a href="https://tracker.c3voc.de/">Tracker</a> project, you can also set the following project property yourself:
				<pre style="color: #ccc; font-size: 0.5em">Publishing.YouTube.Token = <?=h($token)?></pre>
			</p>
		<?php endif ?>
	</body>
</html>
